name: Python application

on:
  # 在push代码到仓库时执行
  push:
  # 定时执行，这里 - cron 配置的就是一个定期执行的表达式
  # 0 0,6,12,18 * * * 表示的在0，6，12，18点整点执行，这里是ISO时间，和国内差8小时
  schedule:
     - cron: '0 0 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        python -m pip install --upgrade requests
        python -m pip install --upgrade datetime
        python -m pip install --upgrade zhdate

    - name: SignIn
      run: |
        python ./main.py