name: Python application

on:
  # 在push代码到仓库时执行
  push:
  # 定时执行，这里 - cron 配置的就是一个定期执行的表达式
  # 0 0,6,12,18 * * * 表示的在0，6，12，18点整点执行，这里是ISO时间，和国内差8小时
  schedule:
     - cron: '0 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 * * *'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install requirements

    - name: Update paper list
      run: |
        python -m pip install --upgrade pip
        python main.py
		
